import NextHead from 'next/head'

const Head = () => {
  return (
    <NextHead>
      <title>th-release.cth</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </NextHead>
  )
}

export default Head;